apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: "{{ .Values.app }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app }}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: dlapp
